# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OdRq3dhAlA01OyHafZQWXtW31fLt1yyJ
"""

from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()
X = data.data
y = data.target

print("Özellik Sayısı:", X.shape[1])
print("Veri Seti Boyutu:", X.shape)
print("Etiketler:", set(y))

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print("Eğitim verisi boyutu:", X_train.shape)
print("Test verisi boyutu:", X_test.shape)

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

model = DecisionTreeClassifier(max_depth=3, random_state=42)
model.fit(X_train, y_train)


y_pred = model.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy (max_depth=3): {acc:.2f}")

depths = range(1, 20)
train_scores = []
test_scores = []

for d in depths:
    m = DecisionTreeClassifier(max_depth=d, random_state=42)
    m.fit(X_train, y_train)
    train_pred = m.predict(X_train)
    test_pred = m.predict(X_test)
    train_scores.append(accuracy_score(y_train, train_pred))
    test_scores.append(accuracy_score(y_test, test_pred))

import matplotlib.pyplot as plt

plt.plot(depths, train_scores, marker='o', label='Eğitim Doğruluğu')
plt.plot(depths, test_scores, marker='s', label='Test Doğruluğu')
plt.xlabel("Max Depth")
plt.ylabel("Doğruluk")
plt.title("Eğitim ve Test Doğrulukları vs Karar Ağacı Derinliği")
plt.legend()
plt.grid(True)
plt.show()

from sklearn.tree import DecisionTreeClassifier, plot_tree
import matplotlib.pyplot as plt

# Modeli oluştur ve eğit (optimum derinlik)
model = DecisionTreeClassifier(max_depth=4, random_state=42)
model.fit(X_train, y_train)

# Karar ağacını çiz
plt.figure(figsize=(22,11))
plot_tree(model,
          filled=True,
          feature_names=data.feature_names,
          class_names=data.target_names,
          rounded=True,
          fontsize=8)  # Fontu küçülttük

plt.show()